name: Daily Commit

on:
  schedule:
    - cron: '30 1 * * *'  # Runs daily at 01:30 UTC

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Commit update by 24f3000719@ds.study.iitm.ac.in
        run: |
          echo "Daily update timestamp: $(date +'%Y-%m-%d %H:%M:%S')" >> daily-update.txt
          git config user.name "github-actions[bot]"
          git config user.email "24f3000719@ds.study.iitm.ac.in"
          git add daily-update.txt
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Daily commit by GitHub Actions at $(date +'%Y-%m-%d %H:%M:%S')"
            git push
          fi
