name: Example Workflow

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 24f3000719@ds.study.iitm.ac.in
        run: echo "Hello, world!"

      - name: prime-cache-9c21b8b
        id: prime-cache-9c21b8b
        uses: actions/cache@v4
        with:
          path: ~/.cache/dependencies
          key: cache-9c21b8b
